image: bradlhart/sample-kv-tables:v0.0.4

ports:
- port: 3000
  onOpen: ignore
- port: 8000
  onOpen: open-preview
- port: 8080
  onOpen: ignore
- port: 8888
  onOpen: ignore
- port: 9876
  onOpen: ignore

tasks:
- before: cd webapp
  init: yarn
  command: nginx -c $PWD/nginx.conf; REACT_APP_IS_GITPOD=true && npx webpack-dev-server
- before: $PWD/docker/deploy_contracts.sh "" IS_GITPOD && cleos wallet unlock --password </password
  command: nodeos --config-dir ~/eosio/chain/config --data-dir ~/eosio/chain/data -e -p eosio --plugin eosio::chain_api_plugin --contracts-console
