image: bradlhart/sample-kv-tables:v0.0.8

ports:
- port: 3000
  onOpen: ignore
- port: 8000
  onOpen: open-preview
- port: 8080
  onOpen: ignore
- port: 8888
  onOpen: ignore
- port: 9876
  onOpen: ignore

tasks:
- before: cd webapp
  init: yarn
  command: nginx -c $PWD/webapp/nginx.conf; yarn run serveInGitPod
- before: chmod 755 $PWD/docker/deploy_contracts.sh && cleos wallet unlock --password </password
  command: $PWD/docker/deploy_contracts.sh "" IS_GITPOD
